#!/bin/bash

while read -p "Uneste fajl ili stande: " file; do
	if [[ "$file" = "stande" ]]; then
		exit 0
	elif [[ -f $file ]]; then
		echo "$file je fajl."
	elif [[ -d $file ]]; then
		echo "$file je direktorijum."
	else
		echo "$file je nesto drugo."
	fi
done
