#!/bin/bash

if [[ "$#" != 2 ]]; then
	echo "Nije tacan broj parametara!"
	exit 1
fi

prognoza=$(grep "$1,$2,12h," prognoza)


mesto=$(grep "$1:" regioni | cut --delimiter ":" --fields 2)
vreme=$(cut --delimiter "," --fields 7 <<< "$prognoza")
ostalo=$(cut --delimiter "," --fields 4,5,6 --output-delimiter " " <<< "$prognoza")
alltemp=$(grep "$1,$2," prognoza | cut --delimiter "," --fields 4 | sort --numeric-sort)
mintemp=$(head --lines 1 <<< "$alltemp")
maxtemp=$(tail --lines 1 <<< "$alltemp")

echo "$1"
echo "$mesto"
echo "$vreme"
echo "$ostalo"
echo "Min $mintemp, maks $maxtemp"
