#!/bin/bash

if [ -z "$1" ]; then
	echo "Niste odredili naziv fajla za citanje!"
	exit
fi

if [ ! -f "$1" ]; then
	echo "Odredjeni fajl za citanje ne postoji!"
	exit
fi

if [ -z "$2" ]; then
	echo "Niste odredili domen za mejl!"
	exit
fi

grep "$2" "$1" | cut -f 1,2,4 -d';' --output-delimiter ' ' | sort -k2
