#!/bin/bash

if [ -z "$1" ]; then
	echo "Niste prosledili ime fajla"
	exit
fi

if [ ! -f "$1" ]; then
	echo "Fajl $1 ne postoji"
	exit
fi

if [ -z "$2" ]; then
	echo "Niste odredili sta se dodaje"
	exit
fi

echo "$2" >> "$1"
